---
title: "Building a Fresh Cow Monitoring Database from scratch using MS Access"
description: |
  A case report I compiled to outline the rationale and workflow of a MS Access database built as a novel Fresh Cow recording, monitoring and regular reporting system for a commercial dairy client.
author:
  - name: Padraig Lucey
    url: https://github.com/padge01
date: 2021-10-29
output:
  distill::distill_article:
    self_contained: false
---

# Introduction

The transition period of a dairy cow is when she transitions from late pregnancy to early lactation and is the time frame when most health issues occur in her lifecycle. This was historically defined as the last 3 weeks of gestation and the first 3 weeks of lactation1, but it has been suggested since to alter this period to the 60 days before calving, and 30 days post-calving a. Our understanding of the metabolic stress of calving and the impact of dry cow management on post-partum disease has expanded, highlighting the need for intensive management considerations through the entirety of the dry period and long into the first lactation. Dairy cows are susceptible to infectious and metabolic disease during this risk period, and the incidence of uterine infection can have long term financial effects because of high treatment costs and reduced reproductive performance later in lactation2.
All dairy cattle experience a period of negative energy balance, insulin resistance, weight loss, reduced feed intake and hypocalcemia immediately prior to and post calving. Dairy cattle experience a decrease in dry matter intake within the last week of gestation, which can persist for up to a week into the lactation3. The energy demands of post-partum galactopoesis in modern, high producing dairy cows require large quantities of carbohydrates and almost all the available body glucose is diverted to the mammary gland. Carbohydrate demands are met by the ruminant through gluconeogenesis in the liver using microbial fermentation products as substrate. Propionic acid is the major volatile fatty acid used for glucose production. However, there is a loss between dietary carbohydrate and rumen fermentation as propionic acid only accounts from one third of the total energy available from the fermentation of carbohydrates in the rumen. Acetic and butyric acid are also produced, which cannot be used for gluconeogenesis4.  

When the energy demand to synthesize milk exceeds the energy intake of the diet a cow enters a state of negative energy balance. This initiates the mobilization of body energy reserves, which exist as adipose tissue. Adipose tissue consists of adipocytes which contain triglyceride molecules, made up of long-chain fatty acids. Breakdown of triglycerides result in the release of non-esterified fatty acids (NEFAs) during the process of lipolysis. These NEFAs are transported out of the adipose cells and made available for energy use by other tissues. NEFAs can also be metabolized by the liver to produce ketone bodies. Blood glucose and liver glycogen stores become diminished during a state of negative energy balance, and in this circumstance NEFA mobilization from adipose tissue increases to offer a supply of cellular energy. When glucose availability is low little glucose is available for the Krebs cycle, resulting in small quantities of citrate leaving the mitochondria for malonyl CoA production. This results in the transport of NEFAs into the mitochondria instead, and mitochondrial metabolism of NEFAs produce glucose and ketone bodies, much of which is produced as acetoacetate. This is then converted to beta-hydroxybutyrate in the liver. These ketone bodies act as a fuel source for muscle and spare glucose requirements. Endocrine changes mediate this response to negative energy balance, with insulin being the primary regulator of blood glucose concentrations. 
As glucose concentrations fall in negative energy balance, insulin concentrations also drop. Insulin suppresses lipolysis, so as its concentration declines NEFA mobilization may increase. When a cow fails to adapt to this state of negative energy balance the diseases of ketosis and fatty liver can result. The amount of adipose tissue, or body condition of a cow can regulate adipose sensitivity and lead to higher levels of NEFA mobilization. Insulin resistance is also a result of over conditioning and obesity in cows, which impacts the concentration of insulin required to lower blood glucose concentration. Insulin resistance lowers the suppression of lipolysis, leading to greater rates of NEFA mobilization4. Inappropriately high blood NEFAs can overwhelm the liver’s processing capacity and lead to the condition of fatty liver. 
	This failure of energy provision leads to a state of ketosis in the dairy animal. Two classifications have been suggested for ketosis, type 1 is when the demand for glucose is higher than the livers capacity for gluconeogenesis and the supply of precursors is insufficient. Blood glucose and insulin levels are low and NEFAs enter the mitochondria to produce large amounts of ketone bodies. This then presents as elevated levels of beta-hydroxybutyrate (BHBA) in blood and usually occurs leading up to the peak of milk production. Type 2 ketosis results from large amounts of NEFAs being delivered to the liver during lipolysis in early lactation. Excess NEFA is converted to triglycerides and stored in liver tissue during this phase. If this is overwhelmed, a cow’s ability to mobilize triglyceride from the liver in the face of high NEFA can be insufficient and fatty tissue infiltrates the liver leading to the fatty liver disease state. While type 1 ketosis occurs in high producing cows who do not meet their metabolic energy demands, type 2 ketosis can be at higher risk in cows who are over-conditioned or experiencing insulin resistance and have a high risk of elevated NEFA circulation in the early post-partum period5. 
Over conditioned cows are at a higher risk of transition period health problems and excessive body condition loss is associated with the occurrence of metabolic and reproductive diseases6. Mobilization of adipose tissue is associated with a dysfunction in immune response and may modulate the risk of infectious disease in this period. The inflammatory process initiates in response to a localized pathogenic invasion by immune and nonimmune cells of affected tissue. This process causes the release of proinflammatory signaling molecules such as cytokines, nitric oxide, and eicosanoids, which act locally on the endothelium to increase blood flow and recruitment of circulatory leukocytes to the site of infection. Neutrophils and macrophages migrate to the site of infection and eliminate pathogens through intracellular mechanisms and phagocytosis. Cytokines and eicosanoids also initiate a systemic inflammatory repose which results in the clinically observable signs of pyrexia and tachycardia. Around the time of parturition, the immune system is compromised and may be inadequate in its appropriate inflammatory response. Mononucleucytes are important in the detection and elimination of pathogen infection and when these cells are compromised long standing or systemic infections may be established3. Adipocytes are the cellular source of many proinflammatory mediators and elevated NEFA concentrations can lead to a chronic inflammatory condition. This inflammatory state can increase the body’s risk of infectious and metabolic disease7. The incidence of a single transition cow disorder is also linked to an increased risk of further health issues, as an episode of retained fetal membranes (RFM) increases the risk of mastitis8, while cows who suffer from ketosis have twice the risk of mastitis9. 
We also know that the increased lipid mobilization driven by lactation energy demands directly decrease the antimicrobial function of immune cells in early lactation, making these cows more susceptible to infectious conditions. Elevated BHB levels are associated with lower function of neutrophil antimicrobial action10. Macrophages and neutrophils also have large energy demands in the form of glucose and states of low blood glucose affect their functional ability. From this we know that a moderate body condition leading up to parturition, as well as appropriate dietary provision is important to regulate the inflammatory suppression caused by this state of negative energy balance. Appetite suppression and reduced dry matter intake is experienced in the last week of gestation, and may persist for a week after calving, which results in low blood glucose and decreased insulin levels.  
Over conditioned cows are also at a higher risk of hypocalcemia10. The onset of milk production at the beginning of lactation increases calcium demand and output. A cow’s daily requirement during the dry period is 30 g/day. This is provided by absorption of calcium from the rumen and intestine, or bone reserves as circulating blood calcium levels are low.  Adult dairy cows maintain a total volume of 17 – 27 g of calcium in their body between plasma, extracellular fluid, and bone. In early lactation an excess 20 – 30 g of calcium are withdrawn from these pools daily. Calcium homeostasis is maintained through absorption of dietary calcium or reabsorption of calcium from bone11. Parathyroid hormone (PTH) is released in response to lowered blood calcium which increases mobilization of calcium from bone and the hydroxylation of 25-hydroxycholecalciferol to 1,25(OH)2D3 in the kidney. This acts to increase intestinal absorption of calcium and reabsorption from bone. The dairy cow’s post-parturition response to decreasing plasma calcium is to increase PTH levels and 1,25(OH)2D3. This increases the rate of intestinal absorption and reabsorption from bone, as well as increased renal tubular reabsorption of calcium, however the cow’s ability to stabilize its blood calcium levels through these processes is limited by the rate at which increased calcium absorption can occur12. 
Failure to respond to the calcium demands of lactation put a cow at risk of developing clinical or subclinical hypocalcemia. Clinical milk fever is usually considered as progressive excitation and weakness leading to recumbency, and if not treated, death. Subclinical hypocalcemia is a low blood calcium concentration without the accompanying clinical signs and can affect a large proportion of cows. Subclinical hypocalcemia is linked the risk of a variety of transition disorders as calcium is essential in muscle, nerve, digestive and cellular function as well as decreasing neutrophil function13. This can reduce feed intake, milk production and immune function while increasing the risk of other metabolic and endocrine disorders14. A common hypocalcemia prevention strategy is the inclusion of dietary anions in the feed of immediately pre-partum cows. Including the anions Cl and S in the diet lowers the strong ion difference of the plasma. This increases the solubility of CO2 in plasma, increasing the partial pressure of CO2 and results in a strong ion metabolic acidosis. Salts of the minerals CaCl2 CaSO4, MgCl2, MgSO4, NH4Cl and (NH4)2SO4 can be fed to achieve this. The risk of clinical milk fever and subclinical hypocalcemia is reduced as metabolic acidosis increases mobilization of calcium from bone independent of PTH, as well as increasing dietary absorption of calcium by increasing plasma 1,25(OH)2D3 and results in effective mitigation of hypocalcemia12. Urine pH levels are an effective method of measuring metabolic acidosis and a urine pH of 5.5 – 7 is effective in preventing milk fever15. 
Post-partum diseases in dairy cows can be common, and their incidence is linked with lasting negative effects on milk productivity, fertility and increased the risk of culling. The endocrine changes associated with parturition, as well as the transient hypocalcemia reduce neutrophil and immune function for up to 2 weeks before and 3 weeks after calving. These mechanisms combined with potential contamination of the uterus during parturition lead to a large risk of a variety of transition period associated diseases. This group of conditions can be regarded as dairy production diseases and include hypocalcemia, ketosis, RFM, metritis, abomasal displacement and laminitis16. Retained fetal membranes is a condition of failure of expulsion of the placenta immediately post parturition and is a significant cause of dairy economic losses. Cows are considered to have RFM if the placenta is retained for more than 24 hours post calving. Cows who experience RFM also have an increased risk of metritis and infertility17. After parturition, the placenta can be considered a “foreign body” and a maternal immune reaction initiates its detachment and expulsion. Interleukin-8 acts as a chemoattractants in the cotyledons of the placenta post calving and attract neutrophils to the uterus and facilitate expulsion by breaking down the attachments, however in immune suppression or dysfunction the concentration of Interleukin-8 and the activity of neutrophils is lower, leading to a failure of placental shedding18. Known risk factors for RFM include short gestation, abortion, twins, dystocia, cesarean section, and immunosuppression. Hypocalcemia may increase the risk of RFM as calcium is required for collagenase activity in placenta detachment, as well as modulating the other risk factors associated with RFM. There are few treatment options available for RFM and management should be focused on the mitigation of the complex of stressful conditions and risk factors leading to RFM. Manual removal of the placenta is a common yet ineffective practice which may lead to more severe uterine infections and should not be utilized. Manual removal usually does not remove all necrotic material and is not an effective way of removing contaminated material from the uterus, while also causing damage to the endometrium and facilitating bacterial invasion. Systemic antimicrobial therapy is the other most common therapy but does not have clear treatment benefits and is usually used in an attempt to prevent or treat a subsequent metritis19. Acute post-partum metritis is a common condition in dairy cows, who’s risk is increased by a previous occurance of RFM. Incidence rates have been reported from 3 - 36% and has a large economic and health impact20. Clinical signs can be pyrexia, fetid vaginal discharge, depression, decreased appetite and reduced milk production. The tissue of the uterus is infiltrated with pathogenic bacteria and becomes swollen and friable. Escherichia coli and Trueperella pyogenes are the most isolated bacteria and this condition is commonly treated with systemic or local antimicrobials. Lochia and uterine discharge are a normal part of post-partum uterine involution and should be correctly distinguished from acute post-partum metritis when choosing antimicrobial treatment candidates to ensure appropriate antimicrobial use. Uterine discharge can be graded as: 1 for normal, not-fetid lochia, 2 for cloudy mucoid discharge, 3 for non-fetid mucopurulent discharge with <50% pus, 4 for fetid mucopurulent white, yellow, or red brown discharge with >50% pus and 5 of fetid, serous, or watery discharge with or without necrotic tissue present. A uterine discharge score of 5 can be considered acute post-partum metritis and should be the target of therapy21. Since the flora of metritis primarily involves anaerobic gram-negative bacteria, targeted spectrum cephalosporin systemic treatment has been found effective. Ceftiofur hydrochloride subcutaneously sid for 5 days at 2.2mg/kg and ceftiofur crystalline free acid at the base of the ear at 6.6 mg/kg and repeated after 72 hours are both labelled and effective in the treatment of clinical metritis and mitigating the impact on reproductive performance20. 
	Clinical ketosis is characterized as circulating elevated blood ketone bodies accompanied with the clinical signs of decreased appetite, weight loss or decreased milk production. Subclinical ketosis is the elevate of blood ketone bodies without these observable signs, but both diseases states are associated with an increased risk of other fresh cow diseases such as metritis, and decreased milk yield, reproductive efficiency and increased culling22. The incidence of subclinical ketosis can have an unrecognized impact on the health and production outcomes of a herd with reported incidences of up to 80%23. Diagnosis of subclinical ketosis is most reliable on blood beta-hydroxybutyrate levels, with a concentration of greater than 1 mmol/dL a commonly used cut off23. Propylene glycol is a long standing and common treatment for clinical ketosis. It increases the plasma glucose concentrations and lowers NEFRA and triglyceride levels, decreasing plasma BHBA. Oral drenching of 300 ml propylene from recognition of subclinical ketosis until resolution has been shown to reduce the risk of clinical ketosis and mitigate reductions in milk yield24. 
The economic goal of the early lactation period is to prepare a cow for conception within 120 days of parturition, corresponding with a lactation length of approximately 400 days. To facilitate this the cow must have the uterine environment and metabolic health that facilitates estrus cycle and the attachment of a new pregnancy. The complex set of metabolic and infectious diseases associated with parturition decrease reproductive efficiency and incur economic losses. Given the multifaceted nature of these health complexes, an appropriate approach is to create a comprehensive management system that monitors the contributing factors while tracking the prevalence of the disease outcomes to assess the success of the system or interventions. Surveying the prevalence of these conditions may allow us to focus on specific aspects of management and detect contributing risk factors early. Routine monitoring of the herd level outcomes allows us to follow and adapt our management program to improve health. To establish a monitoring system all incident of the relevant disease conditions must be recorded and tracked with accompanied clinical exams, as well as deaths and culling due to those conditions. Previously suggested target levels for dairy farms include a RFM prevalance of > 10%, clinical milk fever of > 2% and metritis of > 10%25, however this should be adapted to the realistic targets and performance of an individual herd. Differences in monitoring programs may also reflect in different reported prevalence. Systematic monitoring of subclinical ketosis can result in reported prevalence of up to 40%, compared with estimates of 5 – 10% in less regularly monitoring programs, due to the epidemiology and onset time in lactation of ketosis. Diet consistency and intake should also be measured as a proxy for the health and appetite of cows, as well as regular monitoring of the herd and group level milk production. Body condition scoring provides a fast estimate of the metabolic health, nutrition, and metabolic history of a cow, and when done in series can be used to monitor losses or gain in condition. Body condition scoring (BCS) can be carried out using systematic scoring systems to minimize objectivity and interobserver variation, such as the 1 – 5-point scale that increases in increments of 0.25 condition points b. Extreme body conditions scores (<2, >4) have been associated with disease and adverse health outcomes, while cows in higher body condition have a higher risk of large body condition loss (0.75 – 1 point) which is associated with the incidence of post-partum disease. Calving BCS scores should fall within 3 – 3.25 to mitigate negative health events25. Uterine disease should be performed regularly in the first 10 days of lactation using an appropriate metritis grade scale and rectal palpation or an intravaginal diagnostic tool. This routine screening of fresh cows should include health investigations when necessary and the early intervention on recognition of risk signs. Routine blood glucose monitoring can be used as a screening and diagnostic tool for high cows in high risk of ketosis. A blood glucose of > 50 g/dL can be identified for blood ketone monitoring to save the expense of blood ketone equipment in routine monitoring programs c.
	The goal and expected prognosis of implementing a comprehensive management plan to mitigate stress associated with the transition period is that over time the disease burden on the herd can be established. With an understanding of the full disease burden interventions and management changes can be implemented and evaluated for their impact on the level of disease. Reducing this level of disease by introducing targeted interventions will increase the reproductive efficiency of the herd, the profit of milk production by decreasing the cost of disease and improve the health of the herd. The goal of this case report was to investigate a disease outbreak on a herd and use that incident to evaluate the total disease burden surrounding the risk period and implement a management protocol that would reduce and address the cause of this outbreak. 



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


